### ISSUE TITLE
Maria not joining

### ISSUE THREAD

**Issue by gpodan** [ja2-derek/mod-playable-chars#1]
Started a new game with JA2 Gold (steam version) and stracciatella with some mods.

Mods included are:
playable chars, from russia with love, generous rebels, imp quiz honest answers, o fortuna, nightops maps and kaerer gun pack. (in that load order)

Skyrider joined without problem, i could recruit the miner from drassen but maria does not join.

Got the quest from angel, went to the brothel and disabled alarm and took key, then snook into the back door and sneaked maria out. walked back to angel and after getting the deed and jacket maria just keeps standing there in the shop tried waiting 30 minutes, tried talking to her but she just seems stuck, and keeps repeating the normal dialog when you sneak her out.

Is this a bug in the mod or something conflicting with the mods i'm using?

**Comment by ja2-derek** [comment]
Indeed it sounds like a conflict of PCM and NO maps. Maria is supposed to join the squad once she finishes the NPC script, but it looks like she got stuck in the middle in NO map.

**Comment by gpodan** [comment]
Hmm, guess that means i need to choose one over the other.

Unless there is another easy fix?

**Comment by ja2-derek** [comment]
I don't think there is an easy fix without editing the `.NPC` scripts to update the waypoints for NO maps.

**Comment by ja2-derek** [comment]
The miners should work OK though, as they do not need to move around.

**Comment by gpodan** [comment]
Just tested a new game without the NO maps and can confirm i could now get maria as a team member.

Guess some kind of warning should be placed that those 2 don't work 100% with each other.

**Comment by ja2-derek** [comment]
README updated. Thanks!
